CREATE DATABASE "whereWasRahul";

CREATE SCHEMA WHERE_WAS_RAHUL;

CREATE TABLE WHERE_WAS_RAHUL.PATHS (
   PATH_ID serial,
   START_TIME timestamptz NOT NULL,
   END_TIME timestamptz NOT NULL,
   COORDINATES bigint[2][] NOT NULL,
   ACTIVITY_TYPE text NOT NULL,
   DISTANCE integer,

   CONSTRAINT PATH_ID_PKEY PRIMARY KEY (PATH_ID),
   CONSTRAINT UNIQUE_PATH_START_TIME UNIQUE(START_TIME)

);

CREATE TABLE WHERE_WAS_RAHUL.POINTS(
   POINT_ID serial,
   START_TIME timestamptz NOT NULL,
   END_TIME timestamptz NOT NULL,
   COORDINATES bigint[2] NOT NULL,
   NAME text,
   CATEGORY text,

   CONSTRAINT POINT_ID_PKEY PRIMARY KEY (POINT_ID),
   CONSTRAINT UNIQUE_POINT_START_TIME UNIQUE(START_TIME)
);
